//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingStol
    {
        public int id { get; set; }
        public int idStol { get; set; }
        public System.DateTime DateBooking { get; set; }
        public string ClientFIO { get; set; }
    
        public virtual Stoli Stoli { get; set; }
    }
}
